# PyTorch 101 tutorial - Using tensors
Just a simple tutorial on tensors and stuff

In [1]:
import torch
print(torch.__version__)

0.4.0


## Declaring tensors

First, we need to declare a tensor. There are different ways depending on the initialization

In [4]:
# Empty tensor, uncleaned values
x = torch.empty(5, 3)
# Random values (uniform [0,1] probably)
x = torch.rand(5, 3)
# Zeros, fixing dtype
x = torch.zeros(5, 3, dtype=torch.long)
# Tensor from data
x = torch.tensor([5.5, 3])
# Redeclaring tensor 
x = x.new_ones(5, 3, dtype=torch.double)
# New tensor from existing
x = torch.randn_like(x, dtype=torch.float)

We can also read properties of tensors

In [6]:
# Get size
print(x.size())
# Get dtype
print(x.dtype)

torch.Size([5, 3])
torch.int64


## Basic ops

Next, we want to perform basic operations on tensors

In [8]:
x, y = torch.rand(5, 3), torch.rand(5, 3)
# Add tensors
z = x + y
# We can also use torch.add and use the out parameter
z = torch.empty(5, 3)
torch.add(x, y, out=z)
# Last, we can use in-place addition
y.add_(x)

torch.Size([5, 3])

Remember that any operation using _ is in-place and will modify the calling object. 
Also, torch tensors can use numpy indexing

In [9]:
print(y[:, 1])

tensor([ 0.2517,  0.2452,  0.0110,  0.7497,  0.7425])


Reshaping tensors is quite straight-forward

In [10]:
x = torch.randn(4, 4)
# Reshaping to fixed size
y = x.view(16)
# Reshaping to unconstrained size
z = x.view(-1, 8)
print(y.size(), z.size())

torch.Size([16]) torch.Size([2, 8])


Other basic operations on tensors are declared in the documentation

## Numpy integration
PyTorch works seamlessly with numpy, providing an updated numpy version of tensors.

In [14]:
import numpy as np

# Get the numpy vector
a = torch.ones(2, 2)
b = a.numpy()
print(b)

# Perform addition on a to see changes
a.add_(a)
print(a)
print(b)

# From numpy back to torch
c = np.zeros([2, 2])
d = torch.from_numpy(c)
print(d)

[[1. 1.]
 [1. 1.]]
tensor([[ 2.,  2.],
        [ 2.,  2.]])
[[2. 2.]
 [2. 2.]]
tensor([[ 0.,  0.],
        [ 0.,  0.]], dtype=torch.float64)


## Cuda integration
We can run all these operations in a GPU device, also checking if it is available

In [16]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
    print("No GPU buddy")

No GPU buddy


## Farewell
This was the first part of the PyTorch tutorial in which we try to understand to handle tensors, applying operations and reshaping them.

Next we are going to experiment with the autograd 